CREATE TABLE tblCountry(
   id   VARCHAR(30)
  ,text VARCHAR(100)
);

INSERT INTO tblCountry(id,text) VALUES ('AF','Afghanistan');
INSERT INTO tblCountry(id,text) VALUES ('AX','Aland Islands');
INSERT INTO tblCountry(id,text) VALUES ('AL','Albania');
INSERT INTO tblCountry(id,text) VALUES ('DZ','Algeria');
INSERT INTO tblCountry(id,text) VALUES ('AS','American Samoa');
INSERT INTO tblCountry(id,text) VALUES ('AD','Andorra');
INSERT INTO tblCountry(id,text) VALUES ('AO','Angola');
INSERT INTO tblCountry(id,text) VALUES ('AI','Anguilla');
INSERT INTO tblCountry(id,text) VALUES ('AQ','Antarctica');
INSERT INTO tblCountry(id,text) VALUES ('AG','Antigua And Barbuda');
INSERT INTO tblCountry(id,text) VALUES ('AR','Argentina');
INSERT INTO tblCountry(id,text) VALUES ('AM','Armenia');
INSERT INTO tblCountry(id,text) VALUES ('AW','Aruba');
INSERT INTO tblCountry(id,text) VALUES ('AU','Australia');
INSERT INTO tblCountry(id,text) VALUES ('AT','Austria');
INSERT INTO tblCountry(id,text) VALUES ('AZ','Azerbaijan');
INSERT INTO tblCountry(id,text) VALUES ('BS','Bahamas');
INSERT INTO tblCountry(id,text) VALUES ('BH','Bahrain');
INSERT INTO tblCountry(id,text) VALUES ('BD','Bangladesh');
INSERT INTO tblCountry(id,text) VALUES ('BB','Barbados');
INSERT INTO tblCountry(id,text) VALUES ('BY','Belarus');
INSERT INTO tblCountry(id,text) VALUES ('BE','Belgium');
INSERT INTO tblCountry(id,text) VALUES ('BZ','Belize');
INSERT INTO tblCountry(id,text) VALUES ('BJ','Benin');
INSERT INTO tblCountry(id,text) VALUES ('BM','Bermuda');
INSERT INTO tblCountry(id,text) VALUES ('BT','Bhutan');
INSERT INTO tblCountry(id,text) VALUES ('BO','Bolivia');
INSERT INTO tblCountry(id,text) VALUES ('BA','Bosnia And Herzegovina');
INSERT INTO tblCountry(id,text) VALUES ('BW','Botswana');
INSERT INTO tblCountry(id,text) VALUES ('BV','Bouvet Island');
INSERT INTO tblCountry(id,text) VALUES ('BR','Brazil');
INSERT INTO tblCountry(id,text) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO tblCountry(id,text) VALUES ('BN','Brunei Darussalam');
INSERT INTO tblCountry(id,text) VALUES ('BG','Bulgaria');
INSERT INTO tblCountry(id,text) VALUES ('BF','Burkina Faso');
INSERT INTO tblCountry(id,text) VALUES ('BI','Burundi');
INSERT INTO tblCountry(id,text) VALUES ('KH','Cambodia');
INSERT INTO tblCountry(id,text) VALUES ('CM','Cameroon');
INSERT INTO tblCountry(id,text) VALUES ('CA','Canada');
INSERT INTO tblCountry(id,text) VALUES ('CV','Cape Verde');
INSERT INTO tblCountry(id,text) VALUES ('KY','Cayman Islands');
INSERT INTO tblCountry(id,text) VALUES ('CF','Central African Republic');
INSERT INTO tblCountry(id,text) VALUES ('TD','Chad');
INSERT INTO tblCountry(id,text) VALUES ('CL','Chile');
INSERT INTO tblCountry(id,text) VALUES ('CN','China');
INSERT INTO tblCountry(id,text) VALUES ('CX','Christmas Island');
INSERT INTO tblCountry(id,text) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO tblCountry(id,text) VALUES ('CO','Colombia');
INSERT INTO tblCountry(id,text) VALUES ('KM','Comoros');
INSERT INTO tblCountry(id,text) VALUES ('CG','Congo');
INSERT INTO tblCountry(id,text) VALUES ('CD','Congo}, Democratic Republic');
INSERT INTO tblCountry(id,text) VALUES ('CK','Cook Islands');
INSERT INTO tblCountry(id,text) VALUES ('CR','Costa Rica');
INSERT INTO tblCountry(id,text) VALUES ('CI','Cote D''Ivoire');
INSERT INTO tblCountry(id,text) VALUES ('HR','Croatia');
INSERT INTO tblCountry(id,text) VALUES ('CU','Cuba');
INSERT INTO tblCountry(id,text) VALUES ('CY','Cyprus');
INSERT INTO tblCountry(id,text) VALUES ('CZ','Czech Republic');
INSERT INTO tblCountry(id,text) VALUES ('DK','Denmark');
INSERT INTO tblCountry(id,text) VALUES ('DJ','Djibouti');
INSERT INTO tblCountry(id,text) VALUES ('DM','Dominica');
INSERT INTO tblCountry(id,text) VALUES ('DO','Dominican Republic');
INSERT INTO tblCountry(id,text) VALUES ('EC','Ecuador');
INSERT INTO tblCountry(id,text) VALUES ('EG','Egypt');
INSERT INTO tblCountry(id,text) VALUES ('SV','El Salvador');
INSERT INTO tblCountry(id,text) VALUES ('GQ','Equatorial Guinea');
INSERT INTO tblCountry(id,text) VALUES ('ER','Eritrea');
INSERT INTO tblCountry(id,text) VALUES ('EE','Estonia');
INSERT INTO tblCountry(id,text) VALUES ('ET','Ethiopia');
INSERT INTO tblCountry(id,text) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO tblCountry(id,text) VALUES ('FO','Faroe Islands');
INSERT INTO tblCountry(id,text) VALUES ('FJ','Fiji');
INSERT INTO tblCountry(id,text) VALUES ('FI','Finland');
INSERT INTO tblCountry(id,text) VALUES ('FR','France');
INSERT INTO tblCountry(id,text) VALUES ('GF','French Guiana');
INSERT INTO tblCountry(id,text) VALUES ('PF','French Polynesia');
INSERT INTO tblCountry(id,text) VALUES ('TF','French Southern Territories');
INSERT INTO tblCountry(id,text) VALUES ('GA','Gabon');
INSERT INTO tblCountry(id,text) VALUES ('GM','Gambia');
INSERT INTO tblCountry(id,text) VALUES ('GE','Georgia');
INSERT INTO tblCountry(id,text) VALUES ('DE','Germany');
INSERT INTO tblCountry(id,text) VALUES ('GH','Ghana');
INSERT INTO tblCountry(id,text) VALUES ('GI','Gibraltar');
INSERT INTO tblCountry(id,text) VALUES ('GR','Greece');
INSERT INTO tblCountry(id,text) VALUES ('GL','Greenland');
INSERT INTO tblCountry(id,text) VALUES ('GD','Grenada');
INSERT INTO tblCountry(id,text) VALUES ('GP','Guadeloupe');
INSERT INTO tblCountry(id,text) VALUES ('GU','Guam');
INSERT INTO tblCountry(id,text) VALUES ('GT','Guatemala');
INSERT INTO tblCountry(id,text) VALUES ('GG','Guernsey');
INSERT INTO tblCountry(id,text) VALUES ('GN','Guinea');
INSERT INTO tblCountry(id,text) VALUES ('GW','Guinea-Bissau');
INSERT INTO tblCountry(id,text) VALUES ('GY','Guyana');
INSERT INTO tblCountry(id,text) VALUES ('HT','Haiti');
INSERT INTO tblCountry(id,text) VALUES ('HM','Heard Island & Mcdonald Islands');
INSERT INTO tblCountry(id,text) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO tblCountry(id,text) VALUES ('HN','Honduras');
INSERT INTO tblCountry(id,text) VALUES ('HK','Hong Kong');
INSERT INTO tblCountry(id,text) VALUES ('HU','Hungary');
INSERT INTO tblCountry(id,text) VALUES ('IS','Iceland');
INSERT INTO tblCountry(id,text) VALUES ('IN','India');
INSERT INTO tblCountry(id,text) VALUES ('ID','Indonesia');
INSERT INTO tblCountry(id,text) VALUES ('IR','Iran}, Islamic Republic Of');
INSERT INTO tblCountry(id,text) VALUES ('IQ','Iraq');
INSERT INTO tblCountry(id,text) VALUES ('IE','Ireland');
INSERT INTO tblCountry(id,text) VALUES ('IM','Isle Of Man');
INSERT INTO tblCountry(id,text) VALUES ('IL','Israel');
INSERT INTO tblCountry(id,text) VALUES ('IT','Italy');
INSERT INTO tblCountry(id,text) VALUES ('JM','Jamaica');
INSERT INTO tblCountry(id,text) VALUES ('JP','Japan');
INSERT INTO tblCountry(id,text) VALUES ('JE','Jersey');
INSERT INTO tblCountry(id,text) VALUES ('JO','Jordan');
INSERT INTO tblCountry(id,text) VALUES ('KZ','Kazakhstan');
INSERT INTO tblCountry(id,text) VALUES ('KE','Kenya');
INSERT INTO tblCountry(id,text) VALUES ('KI','Kiribati');
INSERT INTO tblCountry(id,text) VALUES ('KR','Korea');
INSERT INTO tblCountry(id,text) VALUES ('KW','Kuwait');
INSERT INTO tblCountry(id,text) VALUES ('KG','Kyrgyzstan');
INSERT INTO tblCountry(id,text) VALUES ('LA','Lao Peoples Democratic Republic');
INSERT INTO tblCountry(id,text) VALUES ('LV','Latvia');
INSERT INTO tblCountry(id,text) VALUES ('LB','Lebanon');
INSERT INTO tblCountry(id,text) VALUES ('LS','Lesotho');
INSERT INTO tblCountry(id,text) VALUES ('LR','Liberia');
INSERT INTO tblCountry(id,text) VALUES ('LY','Libyan Arab Jamahiriya');
INSERT INTO tblCountry(id,text) VALUES ('LI','Liechtenstein');
INSERT INTO tblCountry(id,text) VALUES ('LT','Lithuania');
INSERT INTO tblCountry(id,text) VALUES ('LU','Luxembourg');
INSERT INTO tblCountry(id,text) VALUES ('MO','Macao');
INSERT INTO tblCountry(id,text) VALUES ('MK','Macedonia');
INSERT INTO tblCountry(id,text) VALUES ('MG','Madagascar');
INSERT INTO tblCountry(id,text) VALUES ('MW','Malawi');
INSERT INTO tblCountry(id,text) VALUES ('MY','Malaysia');
INSERT INTO tblCountry(id,text) VALUES ('MV','Maldives');
INSERT INTO tblCountry(id,text) VALUES ('ML','Mali');
INSERT INTO tblCountry(id,text) VALUES ('MT','Malta');
INSERT INTO tblCountry(id,text) VALUES ('MH','Marshall Islands');
INSERT INTO tblCountry(id,text) VALUES ('MQ','Martinique');
INSERT INTO tblCountry(id,text) VALUES ('MR','Mauritania');
INSERT INTO tblCountry(id,text) VALUES ('MU','Mauritius');
INSERT INTO tblCountry(id,text) VALUES ('YT','Mayotte');
INSERT INTO tblCountry(id,text) VALUES ('MX','Mexico');
INSERT INTO tblCountry(id,text) VALUES ('FM','Micronesia, Federated States Of');
INSERT INTO tblCountry(id,text) VALUES ('MD','Moldova');
INSERT INTO tblCountry(id,text) VALUES ('MC','Monaco');
INSERT INTO tblCountry(id,text) VALUES ('MN','Mongolia');
INSERT INTO tblCountry(id,text) VALUES ('ME','Montenegro');
INSERT INTO tblCountry(id,text) VALUES ('MS','Montserrat');
INSERT INTO tblCountry(id,text) VALUES ('MA','Morocco');
INSERT INTO tblCountry(id,text) VALUES ('MZ','Mozambique');
INSERT INTO tblCountry(id,text) VALUES ('MM','Myanmar');
INSERT INTO tblCountry(id,text) VALUES ('NA','Namibia');
INSERT INTO tblCountry(id,text) VALUES ('NR','Nauru');
INSERT INTO tblCountry(id,text) VALUES ('NP','Nepal');
INSERT INTO tblCountry(id,text) VALUES ('NL','Netherlands');
INSERT INTO tblCountry(id,text) VALUES ('AN','Netherlands Antilles');
INSERT INTO tblCountry(id,text) VALUES ('NC','New Caledonia');
INSERT INTO tblCountry(id,text) VALUES ('NZ','New Zealand');
INSERT INTO tblCountry(id,text) VALUES ('NI','Nicaragua');
INSERT INTO tblCountry(id,text) VALUES ('NE','Niger');
INSERT INTO tblCountry(id,text) VALUES ('NG','Nigeria');
INSERT INTO tblCountry(id,text) VALUES ('NU','Niue');
INSERT INTO tblCountry(id,text) VALUES ('NF','Norfolk Island');
INSERT INTO tblCountry(id,text) VALUES ('MP','Northern Mariana Islands');
INSERT INTO tblCountry(id,text) VALUES ('NO','Norway');
INSERT INTO tblCountry(id,text) VALUES ('OM','Oman');
INSERT INTO tblCountry(id,text) VALUES ('PK','Pakistan');
INSERT INTO tblCountry(id,text) VALUES ('PW','Palau');
INSERT INTO tblCountry(id,text) VALUES ('PS','Palestinian Territory, Occupied');
INSERT INTO tblCountry(id,text) VALUES ('PA','Panama');
INSERT INTO tblCountry(id,text) VALUES ('PG','Papua New Guinea');
INSERT INTO tblCountry(id,text) VALUES ('PY','Paraguay');
INSERT INTO tblCountry(id,text) VALUES ('PE','Peru');
INSERT INTO tblCountry(id,text) VALUES ('PH','Philippines');
INSERT INTO tblCountry(id,text) VALUES ('PN','Pitcairn');
INSERT INTO tblCountry(id,text) VALUES ('PL','Poland');
INSERT INTO tblCountry(id,text) VALUES ('PT','Portugal');
INSERT INTO tblCountry(id,text) VALUES ('PR','Puerto Rico');
INSERT INTO tblCountry(id,text) VALUES ('QA','Qatar');
INSERT INTO tblCountry(id,text) VALUES ('RE','Reunion');
INSERT INTO tblCountry(id,text) VALUES ('RO','Romania');
INSERT INTO tblCountry(id,text) VALUES ('RU','Russian Federation');
INSERT INTO tblCountry(id,text) VALUES ('RW','Rwanda');
INSERT INTO tblCountry(id,text) VALUES ('BL','Saint Barthelemy');
INSERT INTO tblCountry(id,text) VALUES ('SH','Saint Helena');
INSERT INTO tblCountry(id,text) VALUES ('KN','Saint Kitts And Nevis');
INSERT INTO tblCountry(id,text) VALUES ('LC','Saint Lucia');
INSERT INTO tblCountry(id,text) VALUES ('MF','Saint Martin');
INSERT INTO tblCountry(id,text) VALUES ('PM','Saint Pierre And Miquelon');
INSERT INTO tblCountry(id,text) VALUES ('VC','Saint Vincent And Grenadines');
INSERT INTO tblCountry(id,text) VALUES ('WS','Samoa');
INSERT INTO tblCountry(id,text) VALUES ('SM','San Marino');
INSERT INTO tblCountry(id,text) VALUES ('ST','Sao Tome And Principe');
INSERT INTO tblCountry(id,text) VALUES ('SA','Saudi Arabia');
INSERT INTO tblCountry(id,text) VALUES ('SN','Senegal');
INSERT INTO tblCountry(id,text) VALUES ('RS','Serbia');
INSERT INTO tblCountry(id,text) VALUES ('SC','Seychelles');
INSERT INTO tblCountry(id,text) VALUES ('SL','Sierra Leone');
INSERT INTO tblCountry(id,text) VALUES ('SG','Singapore');
INSERT INTO tblCountry(id,text) VALUES ('SK','Slovakia');
INSERT INTO tblCountry(id,text) VALUES ('SI','Slovenia');
INSERT INTO tblCountry(id,text) VALUES ('SB','Solomon Islands');
INSERT INTO tblCountry(id,text) VALUES ('SO','Somalia');
INSERT INTO tblCountry(id,text) VALUES ('ZA','South Africa');
INSERT INTO tblCountry(id,text) VALUES ('GS','South Georgia And Sandwich Isl.');
INSERT INTO tblCountry(id,text) VALUES ('ES','Spain');
INSERT INTO tblCountry(id,text) VALUES ('LK','Sri Lanka');
INSERT INTO tblCountry(id,text) VALUES ('SD','Sudan');
INSERT INTO tblCountry(id,text) VALUES ('SR','Suriname');
INSERT INTO tblCountry(id,text) VALUES ('SJ','Svalbard And Jan Mayen');
INSERT INTO tblCountry(id,text) VALUES ('SZ','Swaziland');
INSERT INTO tblCountry(id,text) VALUES ('SE','Sweden');
INSERT INTO tblCountry(id,text) VALUES ('CH','Switzerland');
INSERT INTO tblCountry(id,text) VALUES ('SY','Syrian Arab Republic');
INSERT INTO tblCountry(id,text) VALUES ('TW','Taiwan');
INSERT INTO tblCountry(id,text) VALUES ('TJ','Tajikistan');
INSERT INTO tblCountry(id,text) VALUES ('TZ','Tanzania');
INSERT INTO tblCountry(id,text) VALUES ('TH','Thailand');
INSERT INTO tblCountry(id,text) VALUES ('TL','Timor-Leste');
INSERT INTO tblCountry(id,text) VALUES ('TG','Togo');
INSERT INTO tblCountry(id,text) VALUES ('TK','Tokelau');
INSERT INTO tblCountry(id,text) VALUES ('TO','Tonga');
INSERT INTO tblCountry(id,text) VALUES ('TT','Trinidad And Tobago');
INSERT INTO tblCountry(id,text) VALUES ('TN','Tunisia');
INSERT INTO tblCountry(id,text) VALUES ('TR','Turkey');
INSERT INTO tblCountry(id,text) VALUES ('TM','Turkmenistan');
INSERT INTO tblCountry(id,text) VALUES ('TC','Turks And Caicos Islands');
INSERT INTO tblCountry(id,text) VALUES ('TV','Tuvalu');
INSERT INTO tblCountry(id,text) VALUES ('UG','Uganda');
INSERT INTO tblCountry(id,text) VALUES ('UA','Ukraine');
INSERT INTO tblCountry(id,text) VALUES ('AE','United Arab Emirates');
INSERT INTO tblCountry(id,text) VALUES ('GB','United Kingdom');
INSERT INTO tblCountry(id,text) VALUES ('US','United States');
INSERT INTO tblCountry(id,text) VALUES ('UM','United States Outlying Islands');
INSERT INTO tblCountry(id,text) VALUES ('UY','Uruguay');
INSERT INTO tblCountry(id,text) VALUES ('UZ','Uzbekistan');
INSERT INTO tblCountry(id,text) VALUES ('VU','Vanuatu');
INSERT INTO tblCountry(id,text) VALUES ('VE','Venezuela');
INSERT INTO tblCountry(id,text) VALUES ('VN','Viet Nam');
INSERT INTO tblCountry(id,text) VALUES ('VG','Virgin Islands}, British');
INSERT INTO tblCountry(id,text) VALUES ('VI','Virgin Islands}, U.S.');
INSERT INTO tblCountry(id,text) VALUES ('WF','Wallis And Futuna');
INSERT INTO tblCountry(id,text) VALUES ('EH','Western Sahara');
INSERT INTO tblCountry(id,text) VALUES ('YE','Yemen');
INSERT INTO tblCountry(id,text) VALUES ('ZM','Zambia');
INSERT INTO tblCountry(id,text) VALUES ('ZW','Zimbabwe');


GO
alter table tbluser
add  CountryId varchar(30) null
GO
alter table tbluser
add IsSendEmail bit
GO
